### ISSUE TITLE
Costume Color Effects All Duplicate Objects

### ISSUE THREAD

**Issue by JamesHoustonDavis** [GK-12/rpi_csdt_community#32]
When I duplicate an object, the color and shade of the original still effects the new object. eg. In the bead loom if I make a duplicate bead I cannot set it's color, and it's color will be whatever the original bead's color is.

**Comment by chuck211991** [comment]
Should be in CSnap repo, but David fixed this in commit https://github.com/GK-12/Snap--Build-Your-Own-Blocks/pull/49
