### ISSUE TITLE
Reopening Projects with Duplicates messes with Costumes and Sounds

### ISSUE THREAD

**Issue by JamesHoustonDavis** [GK-12/rpi_csdt_community#38]
If you create a sprite with a costume, then duplicate it, save, and then reopen the project, the duplicate sprite returns to the turtle costume and you must manually switch it's costume back. Similarly, doing the same thing with sounds, the sounds are removed all together from the sprite and must be re-added.

**Comment by chuck211991** [comment]
+1, can confirm. David, can you fix this one?

**Comment by hughed2** [comment]
Sure, I'll take a look.

**Comment by hughed2** [comment]
Moving the issue to csnap:

https://github.com/GK-12/Snap--Build-Your-Own-Blocks/issues/48
